# Generated by Django 4.0.4 on 2022-05-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('Porcentaje_F', models.IntegerField(max_length=100)),
                ('Pais', models.CharField(max_length=100)),
                ('Universidad', models.CharField(max_length=100)),
                ('Requirimientos', models.CharField(max_length=100)),
                ('Popularidad', models.IntegerField(max_length=100)),
            ],
        ),
    ]
